Remove extra space from basic.sh
This extra space causes issues like this because it seems to split the command into two:

```
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
Command --set not found
```